### ISSUE TITLE
Install error on Debian

### ISSUE THREAD

**Issue by zzxzshiyf** [rubenespadas/DionaeaFR#20]
run `python2.7 setup.py install`

got error: `c++: error: unrecognized command line option '-fstack-protector-strong'`

`error: command 'c++' failed with exit status 1`

i'm not familiar with C++,so can you give some adivce?

g++ version

`g++ (Debian 4.7.2-5) 4.7.2`

**Comment by nullprobe** [comment]
Upgrade your gcc, I think '-fstack-protector-strong' was only implemented from 4.8.x or 4.9.x.

**Comment by zzxzshiyf** [comment]
yes,it's solved by your way.Thanks again for your reply.
